# fly.toml app configuration file generated for zeugmaai on 2026-03-06T05:36:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zeugmaai'
primary_region = 'fra'

[build]

[env]

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'

[checks]